services:
  neo4j:
    image: neo4j:latest
    container_name: alex-database-neo4j
    restart: always
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
      - ./csv:/var/lib/neo4j/import
volumes:
  neo4j_data:
