services:
  neo4j:
    image: neo4j:latest
    container_name: alex-database-neo4j
    restart: always
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
    ports:
      - "6969:7474"
      - "4040:7687"
    volumes:
      - neo4j_data:/data
      - ./csv:/var/lib/neo4j/import
    networks:
      - app_network

  postgres:
    image: postgres:13
    container_name: postgres_etl
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: etl_data
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app_network

  backend:
    build: ./backend
    container_name: express_backend
    restart: always
    depends_on:
      - neo4j
      - postgres
    env_file:
      - .env  # Carga las variables de entorno desde el archivo .env
    networks:
      - app_network
    ports:
      - "${EXPRESS_PORT}:3000"

volumes:
  neo4j_data:
  pgdata:

networks:
  app_network:
    driver: bridge
